create table if not exists public.creators (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  url text not null,
  description text not null,
  "imageURL" text
);

alter table public.creators disable row level security;
