create table if not exists public.creators (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  url text not null,
  description text not null,
  "imageURL" text
);

alter table public.creators enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'creators'
      and policyname = 'Creators are publicly readable'
  ) then
    create policy "Creators are publicly readable"
      on public.creators
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'creators'
      and policyname = 'Creators can be added publicly'
  ) then
    create policy "Creators can be added publicly"
      on public.creators
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'creators'
      and policyname = 'Creators can be updated publicly'
  ) then
    create policy "Creators can be updated publicly"
      on public.creators
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'creators'
      and policyname = 'Creators can be deleted publicly'
  ) then
    create policy "Creators can be deleted publicly"
      on public.creators
      for delete
      to anon, authenticated
      using (true);
  end if;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.creators to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.creators (name, url, description, "imageURL")
select * from (values
  ('MKBHD', 'https://www.youtube.com/@mkbhd', 'Sharp, beautifully produced reviews and explainers about phones, cars, and the future of consumer technology.', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80'),
  ('Kurzgesagt', 'https://www.youtube.com/@kurzgesagt', 'Animated science stories that turn cosmic scale, biology, and philosophy into clear visual essays.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1400&q=80'),
  ('Simone Giertz', 'https://www.youtube.com/@simonegiertz', 'Inventive builds, practical design experiments, and delightfully honest engineering projects.', 'https://images.unsplash.com/photo-1581091215367-59ab6b6f8400?auto=format&fit=crop&w=1400&q=80'),
  ('NPR Tiny Desk', 'https://www.youtube.com/@nprmusic', 'Intimate live performances that make established and emerging artists feel close enough to hear the room.', 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80'),
  ('The Icing Artist', 'https://www.youtube.com/@TheIcingArtist', 'Colorful cake transformations, decorating challenges, and dessert builds with a playful studio feel.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=80')
) as seed(name, url, description, "imageURL")
where not exists (select 1 from public.creators);
